package main

import (
	"context"
	"fmt"
	"os"

	"google.golang.org/genai"
)

// To run this sample with a VertexAI Google Cloud project:
//
// $ export GOOGLE_GENAI_USE_VERTEXAI=true
// $ export GOOGLE_CLOUD_PROJECT=xxxxxxxxx
// $ export GOOGLE_CLOUD_LOCATION=us-central1
// $ gcloud auth application-default login
// $ gcloud services enable aiplatform.googleapis.com
// $ go run . -n=5

func sample5_generateImage(ctx context.Context) error {
	modelName := "gemini-3.1-flash-image"
	prompt := "Create an overly decorated umbrella."
	fmt.Println("Prompt:", prompt)
	fmt.Println()

	config := &genai.GenerateContentConfig{
		ResponseModalities: []string{
			string(genai.ModalityImage),
		},
	}
	result, err := client.Models.GenerateContent(ctx, modelName, genai.Text(prompt), config)
	if err != nil {
		return err
	}

	imageCount := 0
	for _, candidate := range result.Candidates {
		if candidate.Content == nil {
			continue
		}
		for _, part := range candidate.Content.Parts {
			if part.InlineData != nil && part.InlineData.Data != nil {
				ext := "jpg"
				if part.InlineData.MIMEType == "image/png" {
					ext = "png"
				}
				path := fmt.Sprintf("generated_image_%d.%s", imageCount, ext)
				fmt.Println("Writing image to file", path)
				err := os.WriteFile(path, part.InlineData.Data, 0777)
				if err != nil {
					return err
				}
				imageCount++
			}
		}
	}

	if imageCount == 0 {
		return fmt.Errorf("no image was generated by the model")
	}

	//
	// Exercise:
	// write an extremely specific prompt to generate an image.
	//
	// Note that safety filters are very sensitive and often refuse harmless prompts.

	return nil
}
